const Errors = {
    UNKNOW: "UNKNOW",
    INVALID_EMAIL: "INVALID_EMAIL",
    SMALL_NAME: "SMALL_NAME",
    BIG_NAME: "BIG_NAME",
    NULL_VALUE: "NULL_VALUE",
    INVALID_ID: "INVALID_ID",
    EMPTY_NAME: "EMPTY_NAME",
    VERY_SMALL_NAME: "VERY_SMALL_NAME",
    VERY_BIG_NAME: "VERY_BIG_NAME",
    NO_LASTNAME: "NO_LASTNAME",
    INVALID_CHARACTERS: "INVALID_CHARACTERS",
} as const

export default Errors